### ISSUE TITLE
Why Quad9 for Private DNS?

### ISSUE THREAD

**Issue by yourjamesurban** [Scrut1ny/GrapheneOS-Guide#14]
Using Quad9 for Private DNS will bypass any VPN configured on the device, for DNS at least. Is there a reason to explicitly configure a Private DNS server when using an (always-on) VPN on your device? In case it isn't, this might be a worthy note to add.

**Comment by Scrut1ny** [comment]
What you're saying is true and I've known that also, but the only reason I have it there is if you don't have a VPN running. It's not specifically stated though and I should add a little note for that, thanks for bringing this up.
