### ISSUE TITLE
What is the status of Lawnchair launcher app?

### ISSUE THREAD

**Issue by taivlam** [Scrut1ny/GrapheneOS-Guide#6]
I'm not sure what's going on with the Lawnchair app on F-Droid.  When I click on the [link](https://f-droid.org/en/packages/ch.deletescape.lawnchair.plah/) provided, the [F-Droid](https://f-droid.org/en/packages/ch.deletescape.lawnchair.plah/) site says the app is not found.

However, I believe this is Lawnchair's [homepage](https://lawnchair.app/).  Also in the [releases](https://github.com/LawnchairLauncher/lawnchair/releases) on its GitHub repo, there seems to be quite a few pre-releases.

I would just fix the link, but it's not clear if the app will be/will return to F-Droid.  There's this issue (at LawnchairLauncher/lawnchair#1473) about putting the Android 11 version onto F-Droid (so, during 2020-2021), but it's still open.  (Maybe it's on the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) third-party repo?)

(Not sure if you can shed some light on how the updates are on your device, as I don't use Lawnchair.)

**Comment by Scrut1ny** [comment]
I'm not sure on the Lawnchair app situation either, it's definitively confused me also. There is 2 versions of this app, and only pre-releases are getting released. Apparently they took it off the F-Droid store, but I wouldn't know why. Lawnchair 2 was last updated in Dec 4, 2019, even though it's the "new" app I guess. Last release update for v1 of Lawnchair was Jul 23, 2018, but for some reason pre-releases are still getting released very frequently. The last update was actually yesterday! I honestly don't understand whats going on with the project, but personally I use the pre-releases cause everything else is too old and sucks. I use [Obtainium](https://github.com/ImranR98/Obtainium) to obtain the latest pre-release updates for this app.

[GitHub Releases](https://github.com/LawnchairLauncher/lawnchair/releases)
[lawnchair.app](https://lawnchair.app/)
[Lawnchair 2](https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah)
[Lawnchair 14](https://lawnchair.app/downloads)

**Comment by Scrut1ny** [comment]
I just decided to checkout the KISS launcher, it's amazing! I don't know what I've been doing this whole time...

**Comment by taivlam** [comment]
FYI, there's also [Unlauncher](https://jkuester.github.io/unlauncher/), which is on [F-Droid](https://f-droid.org/en/packages/com.jkuester.unlauncher/).  However, I personally use the default AOSP in GOS and don't use other launchers.

**Comment by Scrut1ny** [comment]
Pretty simple launcher, I like it. I used to use the default launcher for a short period of time, but I quickly figured out about custom launchers and icon packs etc. I couldn't go back.
